package day.pkg04;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.driver.OracleDriver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cisco126
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        getTeachersInfoToTable();
        updateTeacherBTN.setEnabled(false);
        removeTeacherBTN.setEnabled(false);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameTXT = new javax.swing.JTextField();
        lastNameTXT = new javax.swing.JTextField();
        genderCMB = new javax.swing.JComboBox<>();
        middleNameTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        universityTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        facultyTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gradeCMB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        salarryTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTXT = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentsTXT = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        removeTeacherBTN = new javax.swing.JButton();
        addNewTeacherBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        updateTeacherBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTBL = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        emailsTBL = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        teacherIdTXT = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        emailsTXT = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_floppy_285657.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton3.setText("jButton3");
        jButton3.setToolTipText("");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("First name");

        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Gender");

        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Last name");

        firstNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTXTActionPerformed(evt);
            }
        });

        lastNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTXTActionPerformed(evt);
            }
        });

        genderCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "-" }));

        middleNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTXTActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Midlle name");

        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("University name");

        universityTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityTXTActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Faculty name");

        facultyTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyTXTActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Grade");

        gradeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Very good", "Good", "Pass", "-" }));

        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("Salary");

        salarryTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarryTXTActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("Address");

        addressTXT.setColumns(20);
        addressTXT.setRows(5);
        jScrollPane2.setViewportView(addressTXT);

        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setText("Comments");

        commentsTXT.setColumns(20);
        commentsTXT.setRows(5);
        jScrollPane3.setViewportView(commentsTXT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(middleNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(firstNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addComponent(lastNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(universityTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(facultyTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gradeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(salarryTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(middleNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(universityTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(facultyTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gradeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(salarryTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Enter keyword");

        searchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_system-search_118797.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(51, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Database Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        removeTeacherBTN.setText("Remove Teacher");
        removeTeacherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTeacherBTNActionPerformed(evt);
            }
        });

        addNewTeacherBTN.setText("Add new Teacher");
        addNewTeacherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTeacherBTNActionPerformed(evt);
            }
        });

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        updateTeacherBTN.setText("Update Teacher");
        updateTeacherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateTeacherBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeTeacherBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNewTeacherBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewTeacherBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateTeacherBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeTeacherBTN)
                .addGap(18, 18, 18)
                .addComponent(saveBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBTN)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        teacherTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        teacherTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTBLMouseClicked(evt);
            }
        });
        teacherTBL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teacherTBLKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teacherTBLKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(teacherTBL);

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        emailsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        emailsTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailsTBLMouseClicked(evt);
            }
        });
        emailsTBL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailsTBLKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailsTBLKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(emailsTBL);

        jLabel12.setText("Teacher Id");

        jLabel13.setText("Teacher email");

        teacherIdTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherIdTXTActionPerformed(evt);
            }
        });

        emailsTXT.setColumns(20);
        emailsTXT.setRows(5);
        jScrollPane5.setViewportView(emailsTXT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(teacherIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Emails", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1455, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Phones", jPanel4);

        jPanel6.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1455, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Subjects", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1455, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Students", jPanel7);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1455, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Send Email", jPanel5);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Students");

        jMenuItem1.setText("jMenuItem1");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTXTActionPerformed

    private void lastNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTXTActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        int id;
        String firstName = firstNameTXT.getText();
        String middleName = middleNameTXT.getText();
        String lastName = lastNameTXT.getText();
        String gender = genderCMB.getSelectedItem().toString();
        String universityName = universityTXT.getText();
        String facultyName = facultyTXT.getText();
        String grade = gradeCMB.getSelectedItem().toString();
        String salary = salarryTXT.getText();
        String address = addressTXT.getText();
        String comments = commentsTXT.getText();

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "hr", "hr");
            Statement st1 = conn.createStatement();
            Statement st2 = conn.createStatement();

            String sql = "select max(teacher_id) from teachers ";
            System.out.println("aaaaaaaaaaaaa");
            ResultSet rs = st1.executeQuery(sql);
            if (rs.next()) {
                System.out.println("bbbbbbbbb");

                id = rs.getInt(1) + 1;
            } else {
                System.out.println("cccccccc");

                id = 1;

            }
            sql = "INSERT INTO teachers " + "VALUES ('" + id + "', '" + firstName + "', '" + middleName + "', '" + lastName + "', '" + gender + "', '" + universityName + "', '" + facultyName + "', '" + grade + "', '" + address + "', '" + comments + "', " + salary + " )";

            st2.executeUpdate(sql);
            System.out.println("asdasds");

            // select teachers info to table
            getTeachersInfoToTable();
            clearTeachersForm();
            JOptionPane.showMessageDialog(rootPane, "A new teacher is added.");

            rs.close();
            st1.close();
            st2.close();

            conn.close();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Database not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "insert SQL error!");
        }


    }//GEN-LAST:event_saveBTNActionPerformed

    private void teacherTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTBLMouseClicked
        // TODO add your handling code here:
//        int teacherId = Integer.parseInt(teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 0).toString());
        updateTeacherBTN.setEnabled(true);
        removeTeacherBTN.setEnabled(true);
        getSelectedTeacherInfoToForm();
        getSelectedTeacherEmailsInfoToTable();

    }//GEN-LAST:event_teacherTBLMouseClicked

    private void middleNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTXTActionPerformed

    private void universityTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityTXTActionPerformed

    private void facultyTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyTXTActionPerformed

    private void salarryTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarryTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarryTXTActionPerformed

    private void teacherTBLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacherTBLKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_teacherTBLKeyPressed

    private void teacherTBLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacherTBLKeyReleased
        // TODO add your handling code here:
        getSelectedTeacherInfoToForm();
        getSelectedTeacherEmailsInfoToTable();

    }//GEN-LAST:event_teacherTBLKeyReleased

    private void emailsTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailsTBLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsTBLMouseClicked

    private void emailsTBLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailsTBLKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsTBLKeyPressed

    private void emailsTBLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailsTBLKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsTBLKeyReleased

    private void teacherIdTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherIdTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherIdTXTActionPerformed

    private void addNewTeacherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTeacherBTNActionPerformed
        // TODO add your handling code here:

        clearTeachersForm();
    }//GEN-LAST:event_addNewTeacherBTNActionPerformed

    private void removeTeacherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTeacherBTNActionPerformed
        // TODO add your handling code here:
        String teacherId = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 0).toString();
        System.out.println("111111");

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "hr", "hr");
            System.out.println("22222");

            Statement st = conn.createStatement();

            String sql = "delete from teachers_emails " + "where teacher_id = '" + teacherId + "'";
            String sql2 = "delete from teachers " + "where teacher_id = '" + teacherId + "'";

            st.executeUpdate(sql);
            st.executeUpdate(sql2);

            System.out.println("3333");
            getSelectedTeacherEmailsInfoToTable();
            // select teachers info to table

            getTeachersInfoToTable();

            JOptionPane.showMessageDialog(rootPane, "A teacher is deleted.");

            st.close();
            conn.close();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Database not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "delete SQL error!");
            System.err.println(ex);
        }
    }//GEN-LAST:event_removeTeacherBTNActionPerformed

    private void updateTeacherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTeacherBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminFrame().setVisible(true);
        });
    }

    // ------------Start Methods declaration 
    void getTeachersInfoToTable() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "hr", "hr");
            Statement st = conn.createStatement();
            String sql = "select * from teachers order by teacher_id";

            ResultSet rs = st.executeQuery(sql);
            teacherTBL.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            conn.close();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Database not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL error!");
        }

    }

    void getSelectedTeacherEmailsInfoToTable() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "hr", "hr");
            Statement st = conn.createStatement();
            String sql = "select * from teachers_emails where teacher_id = " + teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 0) + " order by email";

            ResultSet rs = st.executeQuery(sql);
            emailsTBL.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            conn.close();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Database not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Email SQL error!");
        }

    }

    private void getSelectedTeacherInfoToForm() {
        String firstName = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 1).toString();
        String midlleName = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 2).toString();
        String lastName = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 3).toString();
        String universityName = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 5).toString();
        String facultyName = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 6).toString();
        String salary = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 10).toString();
        String address = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 8).toString();

        Object comments = teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 9);

        firstNameTXT.setText(firstName);
        middleNameTXT.setText(midlleName);
        lastNameTXT.setText(lastName);
        universityTXT.setText(universityName);
        facultyTXT.setText(facultyName);
        salarryTXT.setText(salary);
        addressTXT.setText(address);
        if (comments != null) {
            commentsTXT.setText(comments.toString());

        } else {
            commentsTXT.setText("");
        }

        if (teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 4).toString().equals("Male")) {
            genderCMB.setSelectedItem("Male");
        } else {
            genderCMB.setSelectedItem("Female");

        }
        if (teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 7).toString().equals("Excelent")) {
            gradeCMB.setSelectedItem("Excellent");
        } else if (teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 7).toString().equals("Very good")) {
            gradeCMB.setSelectedItem("Very good");

        } else if (teacherTBL.getValueAt(teacherTBL.getSelectedRow(), 7).toString().equals("Good")) {
            gradeCMB.setSelectedItem("Good");
        } else {
            gradeCMB.setSelectedItem("Pass");
        }
    }

    private void clearTeachersForm() {
        firstNameTXT.setText("");
        middleNameTXT.setText("");
        lastNameTXT.setText("");
        genderCMB.setSelectedItem("-");
        universityTXT.setText("");
        facultyTXT.setText("");
        gradeCMB.setSelectedItem("-");
        salarryTXT.setText("");
        addressTXT.setText("");
        commentsTXT.setText("");
        updateTeacherBTN.setEnabled(false);
    }

    // ------------End Methods declaration                      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewTeacherBTN;
    private javax.swing.JTextArea addressTXT;
    private javax.swing.JTextArea commentsTXT;
    private javax.swing.JTable emailsTBL;
    private javax.swing.JTextArea emailsTXT;
    private javax.swing.JTextField facultyTXT;
    private javax.swing.JTextField firstNameTXT;
    private javax.swing.JComboBox<String> genderCMB;
    private javax.swing.JComboBox<String> gradeCMB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lastNameTXT;
    private javax.swing.JTextField middleNameTXT;
    private javax.swing.JButton removeTeacherBTN;
    private javax.swing.JTextField salarryTXT;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField teacherIdTXT;
    private javax.swing.JTable teacherTBL;
    private javax.swing.JTextField universityTXT;
    private javax.swing.JButton updateTeacherBTN;
    // End of variables declaration//GEN-END:variables

}
